### ISSUE TITLE
Run gulp with error

### ISSUE THREAD

**Issue by AkoWu101** [doug-wade/generator-koa-angular#13]
Get this error. Just type gulp command

web/testKoaAngular/gulpfile.js:57
}
^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)

**Comment by doug-wade** [comment]
Hi there -- thanks for submitting an issue!  I guess I haven't been testing the non-transpiled version as carefully as I should (or, you know, write tests :stuck_out_tongue:). I resolved this in 0.4.3; take it for a spin and let me know if you have any issues.
